#!/bin/sh

export BASEDIR="/docker"
export LOGDIR="${BASEDIR}/log"
[ -d "$LOGDIR" ] mkdir "$LOGDIR"

cleanup() {
	for sv in service/*/; do
		SVNAME=$(basename "$sv")
		echo "stopping service ${SVNAME}..."
		sv exit "$sv" &
	done
}

for sv in service/*/; do
	SVNAME=$(basename $sv)
	echo "starting service ${SVNAME}..."
	SVNAME=$SVNAME runsv "$sv" &
done

trap 'cleanup' SIGTERM SIGINT

wait
