#!/bin/sh

export BASEDIR="/docker"
export LOGDIR="${BASEDIR}/log"

cleanup() {
	for sv in service/*/; do
		SVNAME=$(basename "$sv")
		echo "stopping service ${SVNAME}..."
		sv exit "$sv" &
	done
}

for lsv in service/*/log/; do
	if [ -x "${lsv}/run" ]; then
		cp "${BASEDIR}/logrun" "${lsv}/run"
	fi
done

for sv in service/*/; do
	SVNAME=$(basename $sv)
	echo "starting service ${SVNAME}..."
	SVNAME=$SVNAME runsv "$sv" &
done

trap 'cleanup' SIGTERM SIGINT

wait
